### ISSUE TITLE
Possibility of obtaining Directed cyclic graph

### ISSUE THREAD

**Issue by SaqibMamoon** [azizilab/sdcd#28]
Hi! Thanks for sharing such a comprehensive and complete code. I have some questions if you could please guide.

1) Can we obtain the cyclic graphs, and i the code you mentioned that  "adjacency_dag_at_threshold" is used to remove the cycles, if we don't use this function and finetuning operation, is there a change of obtaining a cyclic graph from the firs stage of the model.

2) The models output adjacency matrix contains the values which are causally connected and zeros at most the the indexes, can we obtain a adjacency matrix which contains all the values of for the nodes even with the week causal connection. 

Thanks a lot! 
warmest regards,

**Comment by justjhong** [comment]
Hi @SaqibMamoon thanks for using our package.

To answer your questions:
1. If you don't use this function then it is indeed possible you will have cycles (if you consider any value > 0 in the adjacency matrix an edge). For the first stage of the model, it is possible we get cycles in the candidate edge set (we strictly prune edges at a fixed threshold, so there is no guarantee of a DAG). It's important to use the  "adjacency_dag_at_threshold" function at the end of the second stage since a cyclic graph would render an invalid generative model (there is no clear way to generate data using this model).
2. Yes, if you run https://github.com/azizilab/sdcd/blob/master/sdcd/models/_sdcd.py#L357 with threshold=False, you will receive the weights of the matrix before thresholding, so you can investigate edges that were pruned by the thresholding operation.

Let me know if you have any other questions!
